name: Django Lint

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: 
    - master
    - develop

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install flake8
        cp BookWorm/settings_exp.py BookWorm/settings.py
    - name: Run Tests
      run: |
        python manage.py test
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m flake8 . --count --select=E,W --show-source --statistics --ignore=E501
        # https://flake8.pycqa.org/en/latest/user/error-codes.html
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics  --ignore=F401,F403,F405,E501
