# Generated by Django 4.0.3 on 2022-03-16 10:22

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('NoteBook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=django_editorjs.fields.EditorJsField(),
        ),
    ]
