# Generated by Django 4.0.3 on 2022-03-17 07:41

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('NoteBook', '0003_noteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
