# Generated by Django 4.0.3 on 2022-03-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoteBook', '0004_alter_note_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='name',
            new_name='title',
        ),
    ]
